name: eos_todolist1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # 이미지 에셋 추가
  assets:
    - assets/images/
    - assets/images/eos_logo.png  # 특정 이미지 파일 추가

  # 폰트 추가
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf